### ISSUE TITLE
Thanks for this unofficial build,i have a few questions to ask

### ISSUE THREAD

**Issue by fejich** [alvaromunoz/chiaki-builds#2]
Thanks for this unofficial build, the original version crashes on my computer
This build works great, streaming PS5 works fine.

### 1）Where are the software settings saved?
If you can export the settings like the Android version
So it is very convenient to switch between different computers to play games
Is there any hope of adding this feature to the PC version?

### 2）What is the difference between the different versions in Release?
+ Chiaki-win_x64-MSYS2-2.1.1.zip
+ Chiaki-win_x64-VC-2.1.1.zip
+ Chiaki-win_x64-VC-Qt6-2.1.1.zip

**Comment by perroboc** [comment]
1. I haven't checked this :( I guess it would be in a standard user folder since it's a QT application.
2. The compilation technology stack.
 
VC is Microsoft Visual C++ compiler (not open source, might have some improvements over other compilers for windows)
MSYS2 is an open source technology stack for windows (think GNU C compiler for windows). Both are using QT5, without changes from the original branch.
VC-QT6 is the original branch, but compiled using VC and QT6: The only changes code-wise is the sound implementation which wasn't compatible from QT5 to QT6.

**Comment by fejich** [comment]
Thanks for your patience

Finally I found the setting data of this software in the registry

`HKEY_CURRENT_USER\Software\Chiaki\Chiaki\settings`
